### ISSUE TITLE
do we have plan to support type: terraform  ?

### ISSUE THREAD

**Issue by amitsehgal** [awslabs/aws-deployment-framework#114]
**type: cc-buildonly** is a great option to run terraform/CDK based stacks. Do we have plan to build terraform a type ? haven't seen a roadmap. Custom resource  vs Terraform..usually prefers terraform for things not available in CFN.

**Comment by bundyfx** [comment]
Hi @amitsehgal 

In regards to terraform, we do have the [custom deploy](https://github.com/awslabs/aws-deployment-framework/blob/master/src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/cc-customdeploy.yml.j2) pipeline type which can be used to deploy Terraform. You can see an outline of how this works in [this PR](https://github.com/awslabs/aws-deployment-framework/pull/90).

As for the CDK, we have a [sample](https://github.com/awslabs/aws-deployment-framework/tree/master/samples/sample-cdk-app) of showing how this works. In the sample it still uses the cloudformation deployment type *(cc-cloudformation pipeline type)* because the build stage of the pipeline *(buildspec.yml)* runs *cdk synth* and outputs the template into a template.yml and passes it to the standard deployment phase. We're doing lots of work now to make CDK support even better and are also reworking all Jinja2 constructs into CDK.

**Comment by amitsehgal** [comment]
Thanks @bundyfx for prompt response....Let me check this out and get back.

**Comment by amitsehgal** [comment]
LGTM

**Comment by sbkok** [comment]
Thank you for your patience. I am happy to inform you that this feature has been [released as part of v3.2.0](https://github.com/awslabs/aws-deployment-framework/releases/tag/v3.2.0) just now.
Please open a new issue if you are experiencing any issues related to this feature.
