### ISSUE TITLE
Add support for multiple deployoment OU in nested structure

### ISSUE THREAD

**Issue by WillBroadbent** [awslabs/aws-deployment-framework#130]
We're looking to implement ADF for our organisation, and at the moment it works pretty well for just our team. In future, if all goes smoothly with our spike, we'll likely be looking to roll this out to multiple teams in the larger group, we wouldn't want to share a deployment account since we need that separation (and there would be a lot of pipelines in there getting cluttered). However we do still share an Organization (billing reasons, Security, etc), and we think it would be great if ADF could support multiple deployment accounts in a similar structure as listed below:

```
+ root org
     + team1
          + deployment
               - tooling-account (isolated to only allow deployment to units within team1)
          + production
               - team1-prod
          + staging
               - team1-staging
     + team2
          + deployment
               - tooling-account (isolated to only allow deployment to units within team2)
          + production
               - team2-prod
          + staging
               - team2-staging
     + team3
          + deployment
               - tooling-account (isolated to only allow deployment to units within team3)
          + production
               - team3-prod
          + staging
               - team3-staging
```

Is this the sort of feature that could be implemented at some point? Its my understanding that currently the tool only supports one deployment account due to the system-parameters upon initialisation.

Another structure that could work, but we aren't sure if its possible/how to implement:

```
+ root org
    + deployment
         - team1-tooling
         - team2-tooling
         - team3-tooling
     + team1
          + production
               - team1-prod
          + staging
               - team1-staging
     + team2
          + production
               - team2-prod
          + staging
               - team2-staging
     + team3
          + production
               - team3-prod
          + staging
               - team3-staging
```

**Comment by bundyfx** [comment]
Hi @WillBroadbentMSM 

This is something we have wanted to do for a while however it is a bit tricky to implement correctly at this stage. Partially because there is no such thing as a OU path based IAM permission, only an organization as a whole. To do this without OU path based permissions, we would need to drop using _OrganizationId_ as a boundary for certain conditions on KMS and S3 Bucket policies and move to implementing single role ARN's from all accounts under a certain tree structure, this in turn leads to hitting the max size of an IAM policy quite easily and removes part of the scalability aspect of ADF. Having multiple deployment accounts is something that we've had on the radar for a long time and is something we will work towards after 1.3.0 as it requires a fair bit of shuffling in regards to SSM Parameters and permissions in general.

**Comment by sbkok** [comment]
I'm closing this issue as it has been inactive for a long time.
As @bundyfx mentioned above, this would be a significant effort to implement, while considering the traction in this issue not a lot of customers require this today.

Please reopen if you think this would be a valid use case to reconsider.
Thank you!
