### ISSUE TITLE
global params files are not properly merged

### ISSUE THREAD

**Issue by vchepkov** [awslabs/aws-deployment-framework#132]
While using ADF 1.2.5 observing the following issue:

created a file global_us-east-1.json:
```
{
    "Parameters": {
        "ExportedResource": "import:accountid:us-east-1:adf-stack:ExportedResource"
    }
}
```

After adf-build/generate_params.py is executed resulting json file has imported parameter outside of Parameters block:

```
{"Parameters": {"params1": "value1"}, "ExportedResource": "resource-id", "Tags": {"tag1": "value1"}}
```

**Comment by bundyfx** [comment]
Fixing this one currently. Also adding in more tests for this moving forward!

**Comment by vchepkov** [comment]
Thank you! The last tagged/published release was 1.2.3, by the way

**Comment by bundyfx** [comment]
> Thank you! The last tagged/published release was 1.2.3, by the way

Thanks! v1.2.6 now an official release.

**Comment by vchepkov** [comment]
We have installed v1.2.6, now imported parameters are completely lost :(

**Comment by bundyfx** [comment]
> We have installed v1.2.6, now imported parameters are completely lost :(

Can you elaborate a bit? the import: intrinsic function works as intended for me, correctly imports the value and replaces the import string in parameter files. is your import in your global.yml? in your stage parameter? is it not replacing anything?

**Comment by vchepkov** [comment]
we have it in 'global'_region file:

> created a file global_us-east-1.json:
>{
>   "Parameters": {
>       "ExportedResource": "import:accountid:us-east-1:adf-stack:ExportedResource"
>    }
>}

I see in build output that imported parameter is properly resolved, but it is not present in final params file at all, whereas before it was added outside of Parameters block

**Comment by bundyfx** [comment]
Very strange, I cannot reproduce this. I have made a simple pipeline to test this just now with two accounts in it (over **two** stages).

I made two parameter files:
- account-2.json
- global_eu-central-1.json

**global_eu-central-1.json** has the following content:

```json
{ 
    "Parameters": { 
        "CostCenter": "import:111111111:eu-central-1:adf-sample-iam:DefaultInstanceManagedProfile", 
        "Environment": "testing" 
    } 
} 
```

**account-2.json** (which targets the account with the same name in the pipeline has the following content:

```json
{ 
    "Parameters": { 
        "Environment": "production" 
    } 
} 
```

When the build stage occurs, _generate_params.py_ runs and creates the unique stage parameter files as expected. The first stage of the pipeline is an account called _account-1_ since there is no parameter file for that account it takes from the global_eu-central-1.json file _(the pipeline stage is in eu-central-1)_ as expected. For the second stage it uses the account-2.json file since that is the name of the account for that stage, this overrides the any of the parameter defined in the _global_eu-central-1.json_ and merged in any that were not defined.

so the file for account account-2.json ends up looking like this:

```json
{ 
    "Parameters": { 
        "CostCenter": "1234", 
        "Environment": "production" 
    } 
} 
```

Where **1234** is the value that was imported from the output *KEY* (not export name) called DefaultInstanceManagedProfile on the cloudformation stack adf-sample-iam in eu-central-1 on the aws account 111111111.

Am I missing something in my simple testing that you are doing in your environment? I'll keep messing around in the meantime, maybe i'll run into something strange.

**Comment by bundyfx** [comment]
> Am I missing something in my simple testing that you are doing in your environment? I'll keep messing around in the meantime, maybe i'll run into something strange.

I was missing something! looks as tho its not merging correctly as you suggested. It doesn't take the values out of global.json into the more specific file. Double checking a few things now!

**Comment by vchepkov** [comment]
Appreciate your prompt responses!

**Comment by bundyfx** [comment]
No worries! Ok think I have it, this time before I make a release, could you test this for me to ensure its working as intended from your perspective?

in resolver.py on line 71 [here](https://github.com/awslabs/aws-deployment-framework/blob/master/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/resolver.py#L71)

this line: 
```python
parent_key = list(Resolver.determine_parent_key(self.stage_parameters, key))[0]
```
should become:

```python
parent_key = list(Resolver.determine_parent_key(self.comparison_parameters, key))[0]
```

This works as intended for me now after making the change, if that is the fix for you also, we just need to change each occurrence of this specific line (_there are 3 in resolver.py, one for each intrinsic function)_ to use comparison params and not stage ones.

**Comment by vchepkov** [comment]
That seems to work fine, but it updated some resources I didn't expect to be updated, still investigating. Maybe tags got lost or appeared, not sure yet.

**Comment by vchepkov** [comment]
Never mind, it was a 'pre-existing' condition :) I think we are good.
What me to update code in two other places and check again?

**Comment by bundyfx** [comment]
No, thats fine. Thanks for testing. I have tested the other two. Making 1.2.7 now.
