### ISSUE TITLE
Deployment Stage names to be based on target OU instead of just a number

### ISSUE THREAD

**Issue by triha74** [awslabs/aws-deployment-framework#139]
I would much rather have the stage names be more specific to where the deployment is instead of just the number so rather `deployment-{target.name}` then `deployment-stage-{i}`

**Comment by bundyfx** [comment]
Agreed, thats why we added the **name:** property to the target object so you can define whichever name you would like for a stage. It defaults to deployment-stage-n because it is truly unique, and stage names must be unique. If we made it based on the name it is possible for duplicates to occur and the pipeline creation to fail.
