### ISSUE TITLE
ADF Account provisioning automation

### ISSUE THREAD

**Issue by bundyfx** [awslabs/aws-deployment-framework#178]
ADF should handle the AWS Account creation process and the automation around moving the new account into the desired Organizational Unit upon creation. This should be a process owned and operated on from within a Pipeline on the master AWS Account.

**Comment by thiezn** [comment]
Hi Flynn,

Would be a great addition indeed! 

I created a python module specific for this purpose. It's pushed to PyPi as a module (can also be used outside of ADF) and code is hosted on github [here](https://github.com/thiezn/awsaccountmgr). Having the functionality in ADF would be preferred, perhaps you can use the code for some inspiration?

Cheers,
Thiezn

**Comment by yawn** [comment]
I think it might make sense to considers ADF's position regarding organisational frameworks (see e.g. #108) before. LZ 1.x, CT and LZ 2.x all implement their own respective / semi-identical account vending mechanisms and despite of it's currently inferior (compared to LZ 2) feature set I believe CT (plus SSO) is the combo that everybody is going use eventually. CT (due to it being a product and not a solution) + ADF is quite an attractive option atm. but does not (and will never) need this feature.
