### ISSUE TITLE
Cross-account CodeBuild deployment

### ISSUE THREAD

**Issue by larsrnielsen** [awslabs/aws-deployment-framework#207]
If I use CodeBuild for deployment then ADF doesn't do cross-account deployment (as specified in target), but instead on the deployment account. Is there a way to fix this?

Lars

pipelines:         
  - name: INF-Sandbox-Policies-CC        
    default_providers:         
      source:         
        provider: codecommit         
        properties:         
          account_id: 123456789012 # The AWS Account where the source code will be in a CodeCommit Repository
      build:
        provider: codebuild        
      deploy:
        provider: codebuild
    targets:         
      - target: 234567890123
        regions: eu-west-1

**Comment by bundyfx** [comment]
Hi @larsrnielsen 

This is intended behavior. The tricky thing with cross account codebuild is that we would need to create other stacks in the target accounts just to host the codebuild project and its supporting resources for each target wish to deploy into for each stage in a pipeline. The current way this works is that you create these stages in your pipeline as you have, which in turn creates codebuild projects to support those stages on the deployment account, if you wanted to execute something on another account (or region) as part of a specific stage you would assume a role into another account as part of your code that executes in codebuild *(thanks to the buildspec file)*. You can pass in environment variables (see docs) into your codebuild execution (via deployment map or buildspec.yml) so that you can access the intended account id's from within the job that runs as an easy way to streamline your assume role automation. 

You can also pass environment variables as part of the specific buildspec file for any given stage see [here](https://github.com/awslabs/aws-deployment-framework/blob/3.0/samples/sample-terraform/my_test_spec.yml) for example of using terraform with ADF which does this sort of thing. 

There are a few challenges with creating codebuild projects remotely on other accounts to execute them as part of a pipeline, but mostly it comes around IAM role and stack management for those other projects. For example, we would need to also create a role on the target account for each stage in the pipeline, what access would that role(s) have? how would it be managed? We want to avoid having some role that runs codebuild executions that has the ability to elevates ones access. The upcoming 3.0 release will make this image a bit more clear with more examples of using third party products in pipelines efficiently and also how to use custom roles in more detail.

Cheers!

**Comment by larsrnielsen** [comment]
I thought the role parameter for CB could be used to specify which service role should be used for the remote CB project. As CP doesn't work with remote CB build actions then I guess an advanced implementation would use Lambdas and Step Functions for triggering and coordination. However, I got around my issue by using CF to create the CB project on the target and then trigger the individual CB project via referenced S3 bucket where I store a configuration file.

**Comment by csmuthukuda** [comment]
> Hi @larsrnielsen
> 
> This is intended behavior. The tricky thing with cross account codebuild is that we would need to create other stacks in the target accounts just to host the codebuild project and its supporting resources for each target wish to deploy into for each stage in a pipeline. The current way this works is that you create these stages in your pipeline as you have, which in turn creates codebuild projects to support those stages on the deployment account, if you wanted to execute something on another account (or region) as part of a specific stage you would assume a role into another account as part of your code that executes in codebuild _(thanks to the buildspec file)_. You can pass in environment variables (see docs) into your codebuild execution (via deployment map or buildspec.yml) so that you can access the intended account id's from within the job that runs as an easy way to streamline your assume role automation.
> 
> You can also pass environment variables as part of the specific buildspec file for any given stage see [here](https://github.com/awslabs/aws-deployment-framework/blob/3.0/samples/sample-terraform/my_test_spec.yml) for example of using terraform with ADF which does this sort of thing.
> 
> There are a few challenges with creating codebuild projects remotely on other accounts to execute them as part of a pipeline, but mostly it comes around IAM role and stack management for those other projects. For example, we would need to also create a role on the target account for each stage in the pipeline, what access would that role(s) have? how would it be managed? We want to avoid having some role that runs codebuild executions that has the ability to elevates ones access. The upcoming 3.0 release will make this image a bit more clear with more examples of using third party products in pipelines efficiently and also how to use custom roles in more detail.
> 
> Cheers!

Hi @bundyfx I'm also trying to implement the same behavior and got stuck because the resource(AWS::IAM::Role) for assuming the role is also created in the same pipeline (just before this step using CF)...so any suggestion how I can get this ARN from cloudformation and access it from codebuild stage.
