### ISSUE TITLE
Account Rename and account Closure

### ISSUE THREAD

**Issue by rahul1285** [awslabs/aws-deployment-framework#258]
Hello Team,
I want to know if the renaming of AWS account and Closure of AWS account is in scope for upcoming Releases in ADF. I have seen a Issue(marked as enhancement )  regarding rename of account sometime back  but I am not able to locate it now under Enhancements. My ADF version is 3.0.5.  Can you pls let me know if these 2 issues are in Scope ? if Yes in which release you are planning to deliver them.

Thanks in Advance.

**Comment by rahul1285** [comment]
Hi Team,
Do we have any update on this?

**Comment by engrun** [comment]
I guess this is not easily implemented as renaming accounts requires root-credentials.

**Comment by deltagarrett** [comment]
Hi @rahul1285 . Exactly as @engrun said this is not achievable at this point in time since renaming an account, changing its email or other privileged operations require root user: https://aws.amazon.com/premiumsupport/knowledge-center/change-organizations-name/ . This is not related to ADF implementation or any improvement, but to the fact that there are no public API for this kind of operations up to now. 

@rahul1285 , do you think we can close the issue and maybe re-open in the future whenever we would have this API available?

**Comment by benbridts** [comment]
Could we pivot this issue to look at ways to have ADF rely less on Account Names? Eg. either using account ids or tags on the account in organizations might solve this issue too?

**Comment by sbkok** [comment]
As mentioned by @deltagarrett, it is not possible to add support for this to ADF today.
Regarding the requests of @benbridts, these features are part v3.2.0.

Hence I am closing this issue. Please open a new issue when the APIs do support changing the account name and email address in the future. Thanks.
