### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by egut** [awslabs/aws-deployment-framework#292]
I know how open source project work, and you guys are doing a great job.

I have seen many nice new features implemented (and some that I want to take advantage of) but I haven't seen any new releases since april. 

What are your current plan for release?

**Comment by sbkok** [comment]
Thanks for your support Erik!
We are actively working towards the next release. My estimate is that we should be able to publish that soon; in the next few weeks at the latest. I will leave this issue open until we have published the next release, so you will be notified directly.

**Comment by caviliar** [comment]
Hello, we are investigating using ADF, and are wondering if this project is still active. I notice there hasn't been a commit in 4 months or a release since April last year. Our aws solutions architect mentioned this tool, but I'd like to know the state of the project before committing to using this.
