### ISSUE TITLE
Tagging OUs with the same tag will break target resolution. 

### ISSUE THREAD

**Issue by StewartW** [awslabs/aws-deployment-framework#296]
If you have a deployment map targeting accounts via tags. (I.e "managed_by_adf: True:) and you tag an Organization unit with the same tag. It will break the target resolution because [the code here](https://github.com/awslabs/aws-deployment-framework/blob/master/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/target.py#L102) is expecting an account id to be returned. 

I think the ideal solution to this is that we allow for tagged OUs, and instead resolve the accounts that are inside it. This would allow for deployment maps that target multiple OUs in the one stage.

**Comment by sbkok** [comment]
Thank you for your patience. I am happy to inform you that this issue is resolved with the release of Wave deployments as part of [release v3.2.0](https://github.com/awslabs/aws-deployment-framework/releases/tag/v3.2.0) just now.
I'm hereby closing this issue. Please open a new issue if you are experiencing any issues related to this feature.
