### ISSUE TITLE
Retry CodeBuild not working 

### ISSUE THREAD

**Issue by kerimk06** [awslabs/aws-deployment-framework#302]
In the 'aws-deployment-framework-bootstrap-pipeline' pipeline, there is a CodeBuild called 'UploadAndUpdateBaseStacks'. When this build fails and press 'Retry' I get the following error: "[Container] 2020/10/28 09:43:24 Waiting for DOWNLOAD_SOURCE NoSuchKey: The specified key does not exist." 

Release change does work. But why is it that the 'Retry' does not. Does it always expect from you to 'Release change' when this build fails?

**Comment by sbkok** [comment]
Hi Kerim, Could you share what was the original issue that caused this issue and what you changed when you hit retry again?
Retrying would/should take the original source and execute.

**Comment by sbkok** [comment]
I'm closing this issue as it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed in the meanwhile.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/awslabs/aws-deployment-framework/releases).

Thank you!
