### ISSUE TITLE
Missing the yarnpkg GPG public key

### ISSUE THREAD

**Issue by jarsto** [awslabs/aws-deployment-framework#325]
Hi there

In the file:
`src/template.yml`
before line 479 should be
`- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -`

Thanks,
JS

**Comment by sbkok** [comment]
Hi JS,

Thanks for reporting, the issue is the expiry date of the GPG key for yarn got extended to 2021.
Since the current key in the CodeBuild image is referring to 2020, it fails to run the apt-get update command.

I'm working on a fix and testing it in my own account at the moment.
For those who are blocked by this issue: I would recommend updating the ADF CloudFormation template in the main/root account to remove the `apt-get update -qq` line.

Many thanks, Simon

**Comment by engrun** [comment]
Hit this blocker before the weekend. 

Another possible workaround : 
Edit the CodeBuild project, and remove the `apt-get update -qq line` from the buildspec.
