### ISSUE TITLE
How can i find the actual version of my ADF

### ISSUE THREAD

**Issue by 20FS21** [awslabs/aws-deployment-framework#330]
Hello,
I would like to update my ADF version.
Could you help me how can I find the actual version of my ADF?
When i will update my ADF i will have the changeset failed in my master account.
It's normal?
Thanks a lot.

**Comment by sbkok** [comment]
Hi @20FS21,

To check the current version of ADF that you have deployed, go to the management account (the one you referenced as master account) and check the CloudFormation stack output or tag of the serverlessrepo-aws-deployment-framework Stack in us-east-1.

In the outputs tab, it will show the version as the `ADFVersionNumber`.
In the tags on the CloudFormation stack, it is presented as `serverlessrepo:semanticVersion`.

You can redeploy/update by deploying the latest version of the serverless application repo. Follow the instructions as written here to do so: [Admin Guide - Updating between ADF versions](https://github.com/awslabs/aws-deployment-framework/blob/master/docs/admin-guide.md#updating-between-versions).
I hope this helps. Please let us know if there are any issues that you are running into that we can help with.

Best regards, Simon

**Comment by 20FS21** [comment]
Thanks a lot i see that the version is 3.0.6.
But the latest version is 3.1.0 correct?
I try to re deploy from SAR the ADF but during the deploy my change set in master account failed.
Status reason
No updates are to be performed.
do you have some idea for fix this?
Thanks a lot.

**Comment by sbkok** [comment]
Yes, 3.1.0 is the latest version.

If you go to the management account in us-east-1:

1. Navigate to the ADF SAR, can be found [here](https://console.aws.amazon.com/lambda/home?region=us-east-1#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:112893979820:applications/aws-deployment-framework).
1. Tick the box at the bottom that states: "I acknowledge that this app creates custom IAM roles and resource policies."
1. Keep all other form fields as is.
1. Click the Deploy button.

This will take a few minutes to deploy and kick-off your SAR deployment using CloudFormation.
Leave the browser window open until it changes pages.

To check the progress in the management account in us-east-1, follow these steps:
1. Go to the [CloudFormation console](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks?filteringStatus=active&filteringText=serverlessrepo-aws-deployment-framework&viewNested=true&hideStacks=false) searching for the aws-deployment-framework stack.
1. Open the stack named: `serverlessrepo-aws-deployment-framework`.
1. In the overview of the stack, it reports it current state, `UPDATE_COMPLETE` with a recent `Updated time` is what you want to see.
1. If it is in progress or if it hasn't applied the update yet, you can go to the `Events` tab to see what is happening and if any error happened. Use the refresh button on the top right of the table to retrieve updates on the stack deployment.

Once finished, you need to merge the pull request after reviewing the changes if any are present. In the management account in us-east-1:
1. Go to the [Pull Request section of the aws-deployment-framework-bootstrap CodeCommit repository](https://console.aws.amazon.com/codesuite/codecommit/repositories/aws-deployment-framework-bootstrap/pull-requests?region=us-east-1&status=OPEN)
1. There might be a pull request if the `aws-deployment-framework-bootstrap` repository that you have has to be updated to apply recent changes of ADF. This would show up with the version that you deployed recently, for example `v3.1.0`.
1. If there is no pull request, happily continue to the next step. If there is, open it and review the changes that it proposes. Once reviewed, merge the pull request to continue.

Confirm the `aws-deployment-framework-bootstrap` pipeline in the management account in us-east-1:
1. Go to the [CodePipeline console for the aws-deployment-framework-boostrap pipeline](https://console.aws.amazon.com/codesuite/codepipeline/pipelines/aws-deployment-framework-bootstrap-pipeline/view?region=us-east-1).
1. This should progress and turn up as green. If any of these steps fail, you can click on the `Details` link to get more insights into the failure. Please report the step where it failed and include a copy of the logs when it fails here.

Once finished, it will trigger the aws-deployment-framework-_pipelines_ pipeline in the _deployment account_ in _your main region_:
1. Open your deployment account.
1. Make sure you are in the main deployment region, where all your pipelines are located.
1. Go to the CodePipeline console and search for `aws-deployment-framework-pipelines`.
1. This should progress and turn up as green. If any of these steps fail, it could be that one of your pipelines could not be updated. You can click on the `Details` link to get more insights into the failure. Please report the step where it failed and include a copy of the logs when it fails here.

If this last pipeline turned green, to be sure that all went well you can release changes in a pipeline of your choice to test them.

I hope these steps help to debug the root cause of your issue. Please let me know what happened and if this fixes it.

Best regards, Simon

**Comment by sbkok** [comment]
@20FS21 did these instructions help to resolve/debug the issue you ran into?

**Comment by sbkok** [comment]
I'm closing this issue as it has been inactive for a few weeks. This probably means that it has been fixed in the meanwhile.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/awslabs/aws-deployment-framework/releases). Thanks!

**Comment by 20FS21** [comment]
Sorry for late i start to follow your guide for update my ADF version.
in the steps : CodePipeline console for the aws-deployment-framework-boostrap pipeline.
My pipeline failed and not green with this error:
2021-03-07 02:14:24,276 \| INFO \| cloudformation \| 111111111111 - Waiting for CloudFormation stack: adf-global-base-deployment in eu-west-1 to reach stack_update_complete \| (cloudformation.py:132)
112 | 2021-03-07 02:15:21,274 \| WARNING \| organizations \| Account 2222222222222 is not an Active AWS Account \| (organizations.py:137)
113 | Traceback (most recent call last):
114 | File "adf-build/main.py", line 348, in <module>
115 | main()
116 | File "adf-build/main.py", line 326, in main
117 | thread.join()
118 | File "/codebuild/output/src866326974/src/adf-build/shared/python/thread.py", line 30, in join
119 | raise self.exc
120 | File "/codebuild/output/src866326974/src/adf-build/shared/python/thread.py", line 20, in run
121 | self.ret = self._target(
122 | File "adf-build/main.py", line 218, in worker_thread
123 | cloudformation.create_stack()
124 | File "/codebuild/output/src866326974/src/adf-build/shared/python/cloudformation.py", line 277, in create_stack
125 | create_change_set = self._create_change_set()
126 | File "/codebuild/output/src866326974/src/adf-build/shared/python/cloudformation.py", line 186, in _create_change_set
127 | self.validate_template()
128 | File "/codebuild/output/src866326974/src/adf-build/shared/python/cloudformation.py", line 128, in validate_template
129 | raise InvalidTemplateError("{0}: {1}".format(self.template_url, error)) from None
130 | errors.InvalidTemplateError: https://s3.amazonaws.com/serverlessrepo-aws-deplo-bootstraptemplatesbucket-3wer2ujxjttz/adf-bootstrap/global.yml: An error occurred (ValidationError) when calling the ValidateTemplate operation: S3 error: Access Denied
131 | For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
132
