### ISSUE TITLE
Bug, using GitHub as pipeline source for multiple pipelines parameters build fails

### ISSUE THREAD

**Issue by niklaswesterstrahlecybercom** [awslabs/aws-deployment-framework#363]
We have an environment where we use one Gitbug repository for pipelines, building parameters fails. It is using wrong path to build parameters, figured a workaround.

Version details:
serverlessrepo:applicationId | arn:aws:serverlessrepo:us-east-1:112893979820:applications/aws-deployment-framework
serverlessrepo:semanticVersion | 3.1.2

Configuration:
pipelines:
  - name: pipeline1
    default_providers:
      source:
        provider: github
        properties:
          branch: main
          repository: aws-infrastructure
          owner: Owner
          oauth_token_path: /adf/github_token
          json_field: token
      build:
        provider: codebuild
        properties:
          spec_filename: folder1/buildspec.yml
      deploy:
        provider: cloudformation
        properties:
            action: replace_on_failure
            stack_name: stack1
            root_dir: folder1
            template_filename: template.yml
    params:  
      restart_execution_on_update: True
    targets:
      - path: /ou/path
        regions: eu-central-1

Files in GitHub, folder per pipeline:

/folder1/buildspec.yml
/folder1/params/global.yml
/folder1/template.yml
/folder2/buildspec.yml
/folder2/params/global.yml
/folder2/template.yml
we can assume rest of repo is empty.

With above config, GitHub access works nicely with the token and get source. Codebuild starts the build, "default build spec":
phases:
  install:
    commands:
      - aws s3 cp s3://$S3_BUCKET_NAME/adf-build/ adf-build/ --recursive --quiet
      - pip install -r adf-build/requirements.txt -q
      - python adf-build/generate_params.py
artifacts:
  files: '**/*'

The generate_params.py doesn't generate params correctly in this case, and cloudformation doesn't receive parameters.

“Action execution failed
File [folder1/params/AccountName_eu-central-1.json] does not exist in artifact [folder1-build]”

Debugging this shows that generate_params.py only accesses /params though from config one would assume it should get those parameters from /folder1/params - so it doesn't find the global.yml and no params are output to cloudformation step.

Workaround:
version: 0.2

phases:
  install:
    commands:
      - aws s3 cp s3://$S3_BUCKET_NAME/adf-build/ adf-build/ --recursive --quiet
      - pip install -r adf-build/requirements.txt -q
      - mkdir params; cp folder1/params/* params/
      - python adf-build/generate_params.py
      - cp params/* folder1/params/
artifacts:
  files: '**/*'

This is not the most elegant way to go around this error in the build phase, but was the fastest to test out. My version 2 would be just running "ln -s folder1/params params", but haven't changed that yet.

Solution could be to add root_dir parameter to build config?

**Comment by sbkok** [comment]
Hi @niklaswesterstrahlecybercom,

If I understand the problem correctly, you have one repository that is shared between multiple pipelines.
Where you try to deploy `folder1` specifically in one pipeline.

You are on the right track. Using the `root_dir` property instructs CloudFormation to look into the right folder.
The only bit you are missing is the buildspec definition to work on that specific folder.

You can find an example of this setup here: https://github.com/awslabs/aws-deployment-framework/blob/master/samples/sample-mono-repo/apps/alpha/buildspec.yml

Note the following lines:

https://github.com/awslabs/aws-deployment-framework/blob/f9ffc7cb41012a9c8607907eccb96adf255b182d/samples/sample-mono-repo/apps/alpha/buildspec.yml#L3-L5

https://github.com/awslabs/aws-deployment-framework/blob/f9ffc7cb41012a9c8607907eccb96adf255b182d/samples/sample-mono-repo/apps/alpha/buildspec.yml#L12

https://github.com/awslabs/aws-deployment-framework/blob/f9ffc7cb41012a9c8607907eccb96adf255b182d/samples/sample-mono-repo/apps/alpha/buildspec.yml#L20-L24

Please let me know if this resolve the issue for you. And if not, what error you run into or maybe how the problem is different.

Best regards,
Simon

**Comment by niklaswesterstrahlecybercom** [comment]
Thanks Simon, this is what I was missing from examples.. Does exactly what I ended up doing also, just with other commands. But solves the issue I had, so I'll close this issue.
