### ISSUE TITLE
Region Europe (Milan)eu-south-1

### ISSUE THREAD

**Issue by 20FS21** [awslabs/aws-deployment-framework#368]
Hello,
Could i use ADF in the region Europe (Milan)eu-south-1?
Thanks a lot.

**Comment by deltagarrett** [comment]
Hi @20FS21 , 

with current release (3.1.2) it is possible to use eu-south-1 as target region, but not as main region. Several deployments are already using Milan as target region. 

Even if CodeCommit, CodeBuild and CodePipeline are available in Milan region a couple of fix are needed in ADF to be used as main region within an opt-in region (https://docs.aws.amazon.com/general/latest/gr/rande-manage.html). 

Just a quick note. If you want to use opt-in regions, you need to opt-in all bootstrapped accounts in the Organizations otherwise bootstrapping phase on the target regions won't complete successfully. 

Happy to help on this phase or collaborate on pull requesting the needed fix.

**Comment by 20FS21** [comment]
Thanks. 
In adfconfig.yml in bootstrap i adding these :
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - af-south-1
    - ap-east-1
    - ap-south-1
    - ap-northeast-3
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-1
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - eu-south-1
    - eu-west-3
    - eu-north-1
    - me-south-1
    - sa-east-1
 But the pipeline of bootstrap in master account filed.
This is the way that you suggest to me to do?
thanks a lot.

**Comment by deltagarrett** [comment]
Yes, this means that all above listed regions must be activated in all your ADF managed accounts of your Organizations otherwise the boostrap pipeline will fail.

**Comment by deltagarrett** [comment]
One more thing @20FS21 , you can follow the workaround here for boostrapping new accounts with opt-in regions: https://github.com/awslabs/aws-deployment-framework/issues/243#issuecomment-863157491 .

**Comment by sbkok** [comment]
I'm closing this issue as it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in the meanwhile.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/awslabs/aws-deployment-framework/releases).

Thank you!
