### ISSUE TITLE
New IAM Role and Policy

### ISSUE THREAD

**Issue by stefl3n** [awslabs/aws-deployment-framework#369]
I have a similar problem of the Issue #316, because I have a custom automation in the deployment account (not inside adf) which needs a specific role with certain policy to automate all.
Can you explain in detail which is the best way to create a new role and new policy in certain OUs or in all Accounts using ADF although this role and its policy are independent from adf?

Thanks,

Stefano

**Comment by deltagarrett** [comment]
Hi @stefl3n , I can see two approaches to accomplish this task. 

1. Setup a pipeline that deploys "in certain OUs or in all Accounts" a CloudFormation stack with roles and related policies. It is quite common to create and "iam" pipeline to create baseline roles (like federation one). Something like

`- name: iam
    default_providers:
      source:
        provider: codecommit
        properties:
          account_id: 012345678912
      build:
        provider: codebuild
      deploy:
        provider: cloudformation
        properties:
          action: replace_on_failure
    params:
      notification_endpoint: notification@endpoint.com
      restart_execution_on_update: true
    regions: eu-west-1
    targets:
      - path: [/ou1, /ou2, /ou3, /ou4, ...]
        name: iam-everywhere`

2. Otherwise you can add this roles as part bootstrap repository. Modifying the `global-iam.yml` (there is already an available commented custom role) or you can create a `global.yml` or `global-iam.yml` for a given OU creating a folder with the same name of the OU in Organizations. This approach is explained here https://github.com/awslabs/aws-deployment-framework/blob/master/docs/admin-guide.md#bootstrapping-inheritance . 

Please let me know if I got what you are trying to achieve.

**Comment by stefl3n** [comment]
Hi @deltagarrett,
We followed the second approach creating a global-iam.yml with a role and a policy similar to the custom role and the custom policy.
It works fine in most of the accounts but in other accounts we have a 'waiter' error when adf try to update policies.

Do you think the first approach is better then the second one? 

I share with you an image with our error, maybe you can understand better the problem.

![newRolePolicy_adf_global_iam_error](https://user-images.githubusercontent.com/48389722/122565923-47282200-d047-11eb-9a97-a16e6a9900e3.PNG)

**Comment by deltagarrett** [comment]
It is pretty weird that the bootstrap is not able to complete properly with your modification. Did you check why CloudFormation is failing in this account? 

Anyway if in the meanwhile you want to proceed on method 2, I would do so.

**Comment by stefl3n** [comment]
Thanks to @deltagarrett the issue is solved.

I recommend anyone else to be careful not to have a role and / or policy with the same name as the one that will create ADF because otherwise it won't be overwritten or taken over (maybe you created it for previous tests).

Thanks so much @deltagarrett for your help.
