### ISSUE TITLE
info about adfconfig.yml

### ISSUE THREAD

**Issue by 20FS21** [awslabs/aws-deployment-framework#399]
Hello team,
could you help me to know exactly which functionality has "action:safe"?

moves:
    - name: to-root
      action: safe  # Can be safe or remove-base

Thanks a lot.

**Comment by deltagarrett** [comment]
Hi @20FS21 , 

you can refer to the documentation in here https://github.com/awslabs/aws-deployment-framework/blob/f60bfaff93fb0d73b46bf7ff332f4c264cd3044d/docs/admin-guide.md#config . 

Basically if you set `safe`, ADF will not remove the global-base stacks when moving the account from the OU to the root of the organizations. This will not touch any other stack deployed by ADF but just the base ones. 

Personally I've always set it to "remove-base" in order to make accounts moving operations clean. Looking forward to someone else experience around this. 

Let me know if this clarify your doubts.

**Comment by 20FS21** [comment]
Thanks a lot.
Have a nice day.

**Comment by sbkok** [comment]
Thanks for raising your question. I'm closing this issue.
Please reopen it if you have more questions about this.
