### ISSUE TITLE
new account problem created with ADF

### ISSUE THREAD

**Issue by 20FS21** [awslabs/aws-deployment-framework#433]
Hello team,
I created the new account perfectly using ADF from scratch. I have only one issue, this account need to put in the specific OU in 
my master account :
accounts:
  - account_full_name: XXXX-hq-de
    organizational_unit_path: /XXX-core
    email: XXXX-hq-de@XXXX
    allow_billing: True
    delete_default_vpc: True
    alias: 
    tags:
      - created_by: adf
But unfortunately Step Function failed in the last step
![image](https://user-images.githubusercontent.com/77515163/151888743-21086b6e-30dc-4fd3-ade2-e609a2790450.png)
With this error:
[ERROR] Exception: State Machine on Deployment account XXXXXXXX has status: FAILED, see logs
Traceback (most recent call last):
  File "/var/task/generic_account_config.py", line 40, in lambda_handler
    step_functions.execute_statemachine()
  File "/opt/python/stepfunctions.py", line 49, in execute_statemachine
    self._wait_state_machine_execution()
  File "/opt/python/stepfunctions.py", line 104, in _wait_state_machine_execution
    raise Exception(

How can i fix it please?

**Comment by StewartW** [comment]
Hey, can you share the exception please. 
Can you also check the CloudFormation stack that would be created in that account and see what the error was?

**Comment by sbkok** [comment]
Hi @20FS21,

The problem seems to be with the `EnableCrossAccountAccess` Step Function in the deployment region of the deployment account. This Step Function is responsible for setting up the trust relationship between the target accounts and the deployment account. If this fails, it will not be able to access the target accounts.

Most likely your deployment account or one of the target accounts has not been bootstrapped yet.

Can you look into the failed execution of the Step Function and share the error message of the Lambda function called `UpdateCrossAccountIAM`?

**Comment by 20FS21** [comment]
the problem resolved thanks a lot.
