### ISSUE TITLE
Procedure to add existing accounts in ADF

### ISSUE THREAD

**Issue by stefl3n** [awslabs/aws-deployment-framework#442]
Is there a guideline on how to add accounts which are joined inside AWS Organizations?

I created the crossAccountAccessRole manually and then I was able to use ADF there but I want to be sure I'm not missing anything.

Let me know!

Thanks a lot.

**Comment by StewartW** [comment]
There's no other work required, ADF will take it from there. 
I'll take a look and see if I can improve the documentation around this. Thanks!

**Comment by sbkok** [comment]
Please follow the instructions as described here: https://github.com/awslabs/aws-deployment-framework/blob/master/docs/admin-guide.md#bootstrapping-accounts

The term used by ADF to adopt an account is bootstrapping it. See the docs referenced above.

Considering the issue was opened a long time ago, I assume you managed to adopt the accounts into ADF.
I will therefore close the issue. Please reopen this issue if it is not resolved, or if you think the docs don't describe it correctly.
