### ISSUE TITLE
Problem with new Iam role trust policy

### ISSUE THREAD

**Issue by AngeloGelmini** [awslabs/aws-deployment-framework#541]
The use of the role OrganizationAccountAccessRole (the role created by AWS Organization) has a problem.
As AWS is warning in the mail: Change to AWS IAM Role Trust Policy Evaluation and in this blog: https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/
from the 21st of september 2022, a role need to be explicit trusted in order to be able to assume itself.

This is appening during the operation in ADF. It seems that during the bootstrap or other task ADF is making this kind of operation.

**Comment by sbkok** [comment]
Hi @AngeloGelmini, thanks for reporting this. I am looking into this. I have been trying to reproduce the issue so I can determine the exact root cause.

Can you help answer the following questions:
1. Do you happen to know the location where this role is assumed by any chance?
2. Do you have a pipeline that targets the deployment account?
3. Do you have a pipeline that targets the management account?

**Comment by AngeloGelmini** [comment]
Hi, I tried with CloudTrail to get evidence and I did not found anything.
Maybe it is a false alarm. I was sure since there should not be anything else (as far as I know) that use that role, but I am not founding an evidence. I close this issue and if I found something clear I will reopen.
