### ISSUE TITLE
ADF aws-deployment-framework-pipelines times out

### ISSUE THREAD

**Issue by Marta-Danelli** [awslabs/aws-deployment-framework#610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello!

I'm running the aws-deployment-framework-pipelines and it times out with no error.

the following command remains pending for about one hour and then the pipeline times out.

`[Container] 2023/02/21 16:38:22 Running command cdk synth --app adf-build/cdk/generate_pipeline_stacks.py 1> /dev/null`

Has anyone come across something similar?

Thank you in advance!

### Expected Behavior

The command [Container] 2023/02/21 16:38:22 Running command cdk synth --app adf-build/cdk/generate_pipeline_stacks.py 1> /dev/null` works

### Current Behavior

The pipeline remains pending on the command 
[Container] 2023/02/21 16:38:22 Running command cdk synth --app adf-build/cdk/generate_pipeline_stacks.py 1> /dev/null`

[currentbehaviour.txt](https://github.com/awslabs/aws-deployment-framework/files/10796403/currentbehaviour.txt)

### Additional Information/Context

[currentbehaviour.txt](https://github.com/awslabs/aws-deployment-framework/files/10796403/currentbehaviour.txt)

### ADF Version

3.1.2

**Comment by StewartW** [comment]
Hey Marta, 
Pipelines timing out is an issue that we are aware of. (From the log output, I can see you have a few accounts.) 
The good news is that this was fixed in version 3.2.0 that was released a few weeks ago. One of the major improvements we brought in was how pipelines are managed. Removing the bottleneck of generating the stacks on the single CodeBuild instance.
