### ISSUE TITLE
[Feat]: Update CDK Sample App to modern version

### ISSUE THREAD

**Issue by javydekoning** [awslabs/aws-deployment-framework#618]
### Describe the feature

The sample code is still referencing node v8 and an old version of CDK

### Use Case

N/A

### Proposed Solution

Update https://github.com/awslabs/aws-deployment-framework/blob/f60bfaff93fb0d73b46bf7ff332f4c264cd3044d/samples/sample-cdk-app/package.json 

### Acknowledgements

- [X] I may be able to implement this feature request

**Comment by pergardebrink** [comment]
How are people generally using CDK together with ADF pipelines?

We have a solution I have developed that uses CDK in ADF pipelines, where we create account agnostic stacks with the [BootstraplessStackSynthesizer](https://github.com/aws-samples/cdk-bootstrapless-synthesizer) and then push all the assets to centrally managed S3 buckets (one per region in the deployment account instead of the one per "target" account/region that CDK normally does) using [cdk-assets](https://www.npmjs.com/package/cdk-assets).

Everything is managed in the buildspec.yml, together with some SSM Parameters it fetces to setup all environment variables for the BootstraplessSynthesizer correctly and then it's as simple as running` cdk synth` and `cdk-assets publish` for all asset json files. 

I considered also writing a custom CDK pipeline type for ADF also that would encapsulate the complexity away from buildspec, but haven't gotten that far.. 

Sample buildspec with some stuff removed just to show how the implementation kind of looks like:
[samplebuildspec.txt](https://github.com/awslabs/aws-deployment-framework/files/11559887/samplebuildspec.txt)

Btw, my issue here https://github.com/awslabs/aws-deployment-framework/issues/620 is to be able to remove the first hacky line in the install section :) 

I'd be happy to provide a PR with a full sample on how I implemented that, but not sure if there are other better ways to do this instead?
