### ISSUE TITLE
StateMachine PipelineDeletionStateMachine is in failed

### ISSUE THREAD

**Issue by americanjohnny1988** [awslabs/aws-deployment-framework#737]
Hi, we are experiencing an issue with ADF. The mentioned state machine is always in failed status with this error:
User: arn:aws:sts::<accountIDmasked>:assumed-role/adf-global-base-deploymen-DeletionStateMachineExec-1WORZYK7TQJZB/bcpAMdHdbXDVBdhlBZWBdJkRasbbgpNT is not authorized to perform: cloudformation:DeleteStack on resource: arn:aws:cloudformation:eu-west-1:<accountIDmasked>:stack/adf-pipeline-adf-state-backup/* because no identity-based policy allows the cloudformation:DeleteStack action
The iam role permission for this role is ok. There is no SCP which is blocking. Moreover, the adf-pipeline-adf-state-backup is the CF stack used for deploying some AWS Backup plans in all the account, so this should not be deleted.

**Comment by sbkok** [comment]
Thank you for reporting this issue and taking the time to investigate in a call.

The issue was caused by stale deployment pipeline region SSM parameters.
With the fixes introduced in #535 and released as part of v3.2.0, these get deleted after deleting the CloudFormation stack. Before v3.2.0, there was a bug that did not effectively delete the SSM parameters.
Regarding the issue above, these stale SSM parameters were left behind and went undetected until yesterday.

For others that run into a similar issue, this is how you can check:
1. In the deployment account, main deployment region, navigate to the PipelineDeletionStateMachine in AWS Step Functions, open the last execution.
1. Look at which ADF pipelines failed to perform the CloudFormation Delete Stack operation.
1. For each of the failed pipelines, check if the CloudFormation stack exists, named `adf-pipeline-${pipeline-name-goes-here}`.
1. If the stack exists, stop here and report a new issue.
1. If the stack does not exist, while it attempts to delete it, go to AWS Systems Manager.
1. Go to Parameter Store.
1. Filter the parameters, search for `/deployment/S3/${pipeline-name-goes-here}/regions`. Please note, pipeline-name-goes-here does not start with `adf-pipeline-`. Use the name that follows that prefix.
1. Delete the SSM Parameter.
1. Trigger a new change in the AWS CodePipeline named `aws-deployment-framework-pipelines`.

The issue was resolved using the steps listed above.
