### ISSUE TITLE
Silently failing to create github-cloudformation pipeline

### ISSUE THREAD

**Issue by itsdalmo** [awslabs/aws-deployment-framework#9]
Hi!

We are attempting to switch from CodeCommit to Github as the source (`github-cloudformation`) for a pipeline in our `deployment_map.yml`. The commit which implements this change has been picked up by `deployment-framework-pipelines` in CodePipeline and runs/exits without error, however, it does not create the expected deployment pipeline.

I wish I could give more information, since presumably an error has occurred somewhere, but nothing is being logged in the `CreateOrUpdatePipelines` stage of the pipeline which might suggest whats going wrong 😅

**Comment by bundyfx** [comment]
Hello,

In 0.2.0 we have updated the way CloudFormation CreateChangeSet errors were handled to make it more informative when an error was to occur. In your current situation, it sounds like a Change Set is being created on the pipeline stack but is failing to create the change set due to some error occurring. 

Once it failed, it was being cleaned up before you could check why the change set creation was failing. This might be due to missing the parameters in parameter store that the GitHub j2 template is expecting (auth token, web hook secret). Ensure you have created the required parameters in parameter store as outlined in the docs (also updated in 0.2.0).

I have created a CodeCommit based pipeline and then updated it to a GitHub pipeline in the current 0.2.0 release without an error occurring, I’ve also tested a failure (not adding required parameters to Parameter Store) and ensured the stack errors as intended.

There was also a small fix in 0.2.0 for the github-cloudformation.j2 template which resolves an issue with branches not triggering the webhook correctly so please try with the latest set of changes and let me know if this resolves the problem.

**Comment by itsdalmo** [comment]
What you are saying makes a lot of sense @bundyfx, and with #10 it should no longer be silently failing, so this issue can be closed. Thank you for the quick response 🙌
